{{ if and .Values.galaxy_admin_email (and .Values.galaxy_admin_password .Values.galaxy_api_key) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: galaxy-admin-user
  annotations:
     "helm.sh/hook": pre-install
data:
  email: {{ quote .Values.galaxy_admin_email }}
  user: {{ quote .Values.galaxy_admin_username }}
{{ end }}
