{{ if .Values.galaxy_create_pvc }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{.Values.galaxy_pvc}}
  {{ if .Values.pv_minikube }}
  annotations:
      volume.beta.kubernetes.io/storage-class: ""
  {{ end }}
spec:
  {{ if .Values.pv_minikube }}
  selector:
    matchLabels:
      app: {{ .Values.galaxy_label_app }}
  {{ end }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.galaxy_pvc_capacity}} 
{{ end }}
